### ISSUE TITLE
Doesn't run in Node.js 12.x

### ISSUE THREAD

**Issue by jineshshah36** [gajus/fast-printf#3]
Hi,

First off thanks for the awesome libs you've made!

I recently found that I ran into an issue with slonik that I traced back to this lib. It seems that the ts compile target for this lib is es2020 which seems to leave optional chains like found [here](https://github.com/gajus/fast-printf/blob/25d1d0287e5668dcc29eabffe3b904049f9b1261/src/createPrintf.ts#L60). It looks like slonik depends on roarr which depends on this lib. As a result, when I try to import slonik in node 12, it throws an error.

Please let me know if there is anything further I can provide, but I believe simply change the ts compile target to a lower es version should solve the problem

**Comment by gajus** [comment]
What should be the target to make this work?

**Comment by jineshshah36** [comment]
We target es2019 on node 12 in our services. I believe that should work for as well

**Comment by jineshshah36** [comment]
As a follow-up it looks like you have a circular dependency as well. roarr depends on fast-printf and fast-printf depends on roarr. I forked this repo to make the changes and run the tests but because of the circular dependency, it's throwing when it imports roarr since roarr is installing an older version of fast-printf which has the compile target issue. I would consider dropping roarr or making it an optional dependency.

**Comment by jineshshah36** [comment]
I'm happy to put together a PR for you to review with these changes. My main goal is to use slonik on node. 12 which this package now makes difficult.

**Comment by gajus** [comment]
This should be fixed now.
