### ISSUE TITLE
fast-printf fails to install in node < 16

### ISSUE THREAD

**Issue by pmarrone** [gajus/fast-printf#6]
fast-printf started failing to install in an older node version with the following message.

`error boolean@3.1.3: The engine "node" is incompatible with this module. Expected version ">= 16.7.0". Got "12.22.1"`

This happens because of a downstream dependency as reported here
https://github.com/thenativeweb/boolean/issues/317
The dependency to boolean doesn't seem pinned in the package.json, so this happenned.

**Comment by gajus** [comment]
It has been fixed in https://github.com/thenativeweb/boolean/issues/317#issuecomment-902280794

**Comment by pmarrone** [comment]
Thank looking into this.
